# Generated by Django 4.1.2 on 2022-11-13 11:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_product_category_product_status_product_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=40, null=True)),
                ('time', models.CharField(max_length=12, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('paymentslip', models.ImageField(blank=True, null=True, upload_to='paymentslip/')),
                ('last4', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('bank', models.CharField(choices=[('Kasikorn Bank', 'Kasikorn Bank'), ('Bangkok Bank', 'Bangkok Bank'), ('Krungthai Bank', 'Krungthai Bank'), ('Krungsri Bank', 'Krungsri Bank'), ('TTB Bank', 'TTB Bank'), ('SCB Bank', 'SCB Bank'), ('Other Bank form list', 'Other Bank form list')], max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
